apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: finance-manager
data:
  DB_URL: jdbc:postgresql://postgres:5432/finance_manager
  DB_DRIVER: org.postgresql.Driver
  JPA_DDL_AUTO: update
  JPA_SHOW_SQL: "false"
  JPA_FORMAT_SQL: "true"
  JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect